# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: colin_morris
email:
description: >
    Splashing around in the shallow end of the deep learning pool.
baseurl: ""
url: "http://colinmorris.github.io"
permalink: /blog/:title
twitter_username: 
github_username: colinmorris

# Build settings
markdown: kramdown

highlighter: rouge
